CREATE TABLE aka_name (id number NOT NULL PRIMARY KEY, person_id number NOT NULL, name varchar2(4000) NOT NULL, imdb_index varchar2(12), name_pcode_cf varchar2(5), name_pcode_nf varchar2(5), surname_pcode varchar2(5), md5sum varchar2(32));
CREATE TABLE aka_title (id number NOT NULL PRIMARY KEY, movie_id number NOT NULL, title varchar2(4000) NOT NULL, imdb_index varchar2(12), kind_id number NOT NULL, production_year number, phonetic_code varchar2(5), episode_of_id number, season_nr number, episode_nr number, note varchar2(4000), md5sum varchar2(32));
CREATE TABLE cast_info (id number NOT NULL PRIMARY KEY, person_id number NOT NULL, movie_id number NOT NULL, person_role_id number, note varchar2(4000), nr_order number, role_id number NOT NULL);
CREATE TABLE char_name (id number NOT NULL PRIMARY KEY, name varchar2(4000) NOT NULL, imdb_index varchar2(12), imdb_id number, name_pcode_nf varchar2(5), surname_pcode varchar2(5), md5sum varchar2(32));
CREATE TABLE comp_cast_type (id number NOT NULL PRIMARY KEY, kind varchar2(32) NOT NULL);
CREATE TABLE company_name (id number NOT NULL PRIMARY KEY, name varchar2(4000) NOT NULL, country_code varchar2(255), imdb_id number, name_pcode_nf varchar2(5), name_pcode_sf varchar2(5), md5sum varchar2(32));
CREATE TABLE company_type (id number NOT NULL PRIMARY KEY, kind varchar2(32) NOT NULL);
CREATE TABLE complete_cast (id number NOT NULL PRIMARY KEY, movie_id number, subject_id number NOT NULL, status_id number NOT NULL);
CREATE TABLE info_type (id number NOT NULL PRIMARY KEY, info varchar2(32) NOT NULL);
CREATE TABLE keyword (id number NOT NULL PRIMARY KEY, keyword varchar2(4000) NOT NULL, phonetic_code varchar2(5));
CREATE TABLE kind_type (id number NOT NULL PRIMARY KEY, kind varchar2(15) NOT NULL);
CREATE TABLE link_type (id number NOT NULL PRIMARY KEY, link varchar2(32) NOT NULL);
CREATE TABLE movie_companies (id number NOT NULL PRIMARY KEY, movie_id number NOT NULL, company_id number NOT NULL, company_type_id number NOT NULL, note varchar2(4000));
CREATE TABLE movie_info (id number NOT NULL PRIMARY KEY, movie_id number NOT NULL, info_type_id number NOT NULL, info varchar2(4000) NOT NULL, note varchar2(4000));
CREATE TABLE movie_info_idx (id number NOT NULL PRIMARY KEY, movie_id number NOT NULL, info_type_id number NOT NULL, info varchar2(4000) NOT NULL, note varchar2(4000));
CREATE TABLE movie_keyword (id number NOT NULL PRIMARY KEY, movie_id number NOT NULL, keyword_id number NOT NULL);
CREATE TABLE movie_link (id number NOT NULL PRIMARY KEY, movie_id number NOT NULL, linked_movie_id number NOT NULL, link_type_id number NOT NULL);
CREATE TABLE name (id number NOT NULL PRIMARY KEY, name varchar2(4000) NOT NULL, imdb_index varchar2(12), imdb_id number, gender varchar2(1), name_pcode_cf varchar2(5), name_pcode_nf varchar2(5), surname_pcode varchar2(5), md5sum varchar2(32));
CREATE TABLE person_info (id number NOT NULL PRIMARY KEY, person_id number NOT NULL, info_type_id number NOT NULL, info varchar2(4000) NOT NULL, note varchar2(4000));
CREATE TABLE role_type (id number NOT NULL PRIMARY KEY, role varchar2(32) NOT NULL);
CREATE TABLE title (id number NOT NULL PRIMARY KEY, title varchar2(4000) NOT NULL, imdb_index varchar2(12), kind_id number NOT NULL, production_year number, imdb_id number, phonetic_code varchar2(5), episode_of_id number, season_nr number, episode_nr number, series_years varchar2(49), md5sum varchar2(32));
